menu:
    Data Engineering: https://anelen.co/data-engineering.html
    Analytics: https://anelen.co/analytics.html
    Statistics and Machine Learning: https://anelen.co/stats_ml.html
    Our Story: https://anelen.co/about.html
    Open Source: https://anelen.co/open-source.html
    Articles: /index.html

# Copyright Infomation
startyear: 2017

