menu:
    Custom ETL: https://anelen.co/custom-etl.html
    Our Story: https://anelen.co/about.html
    Open Source: https://anelen.co/open-source.html
    Articles: /index.html
    Clients Only: https://anelen.co/clients.html
services:
    Data Engineering: https://anelen.co/data-engineering.html
    Analytics: https://anelen.co/analytics.html
    Statistics and Machine Learning: https://anelen.co/stats_ml.html

# Copyright Infomation
startyear: 2017

