menu:
    Data Engineering: https://anelen.co/data-engineering.html
    Analytics: https://anelen.co/analytics.html
    Statistics and Machine Learning: https://anelen.co/stats_ml.html
    Our story: https://anelen.co/about.html
    Articles: https://articles.anelen.co/index.html

# Copyright Infomation
startyear: 2017
